- hosts: bastion
  become: true 

  tasks: 
    - name: Copy SSH Key
      copy:
        src: ~/.ssh/id_rsa
        dest: ~/.ssh/id_rsa
        owner: root
        mode: 0600
    #- name: Deactivate Public Gateway after reboot
    # shell: sysctl -w net.ipv4.ip_forward=1
    #  shell: echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.d/ip_forward.conf
    #- name: Deactivate Public Gateway after reboot
    #  shell: sysctl -w net.ipv4.ip_forward=1
     # shell: echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.d/ip_forward.conf        